name: Build Control Panel

on:
  push:
    branches:
      - main
    paths:
      - 'control_panel/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-app.yml
    with:
      app-name: control_panel
      app-folder: control_panel
    secrets: inherit